# Generated by Django 4.0.4 on 2022-05-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_apikey_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
