# Generated by Django 4.0.4 on 2022-05-20 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apparel',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.product')),
                ('stocks', models.IntegerField(default=0)),
                ('stockm', models.IntegerField(default=0)),
                ('stockl', models.IntegerField(default=0)),
                ('stockxl', models.IntegerField(default=0)),
                ('stockxxl', models.IntegerField(default=0)),
            ],
            bases=('base.product',),
        ),
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.product')),
                ('stock38', models.IntegerField(default=0)),
                ('stock39', models.IntegerField(default=0)),
                ('stock40', models.IntegerField(default=0)),
                ('stock41', models.IntegerField(default=0)),
                ('stock42', models.IntegerField(default=0)),
                ('stock43', models.IntegerField(default=0)),
                ('stock44', models.IntegerField(default=0)),
                ('stock45', models.IntegerField(default=0)),
            ],
            bases=('base.product',),
        ),
    ]
